### ISSUE TITLE
RP2350

### ISSUE THREAD

**Issue by monpiere** [awawa-dev/HyperSerialPico#35]
I've got a new Raspberry Pi Pico 2 RP2350 on the way and wanted to know if It would need any special programming to work with HyperHDR. Any help you can give would be appreciated. Thanks!

**Comment by awawa-dev** [comment]
The firmware for the RP2040 will not work on the RP2350: you need to recompile it and change the platform from RP2040 to RP2350 using the newer Pico SDK 2.0 (not tested by me). Since the quality control was probably lagging when the new Pico version was made (https://forums.raspberrypi.com/viewtopic.php?t=376248 and probably other unconfirmed issues), I will wait a long time for later improved versions myself.
